name: 'Generate Coverage Report'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage on Ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 and Maven
        uses: s4u/setup-maven-action@v1.15.0
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Generate coverage with JaCoCo
        run: mvn clean verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./target/site/jacoco/jacoco.xml
